#!/bin/bash

# LLAMA AL SCRIP DE INSTALACION SEGUN LA DISTRIBUCION DE LINUX
# Pascual Martinez Cruz --> pascual89@hotmail.com

appinstall=`pwd`

while $verdadero;do
	
	clear
	more logo.txt
	echo ""
	echo "--------------------INSTALACION DE LINUX-CDGRAB----------------------"
	echo "--------Teclee el numero de opcion para instalar Linux-Cdgrab--------"
	echo "Linux--> Opcion estandar; GoboLinux --> Para Gobolinux"
	echo "Opciones: 1.- Linux, 2.- Gobolinux, 0.- Salir"
	read instalacion

	case $instalacion in

		1)
			if ! test -d /System && ! test -d /Users &&  ! test -d /Library;then
				$appinstall/instalar.linux
				break
			else
				echo "Su distribucion no es Linux"
				echo "Elija la opcion numero 2"
				echo ""
				echo "Pulse una Intro para continuar"
				read xxxx
			fi
		;;

		2)  
			if test -d /System && test -d /Programs && test -d /Mount;then
				$appinstall/instalar.gobolinux
				break
			else
				echo "Su distribucion no es GoboLinux"
				echo "Elija la opcion numero 1"
				echo ""
				echo "Pulse una Intro para continuar"
				read xxxx

			fi
		
		;;

		0)
			break
		;;

		*)	
			echo "Opcion no valida"
			sleep 0.5
			continue
		;;
	esac
done
