#!/bin/bash

####################################################
#				       		   #
#		LINUX - CDGRAB 0.5 r2		   #
# Pascual Martínez Cruz -> pascual89@hotmail.com   #
#                 20 - Febrero - 2020              #
#				       		   #
# Shell Script para la grabación de discos ópticos #
#	 Distribuir bajo licencia GPL v2.	   #
#						   #
####################################################

#	Directorios usados por la aplicacion

# linux_dir
# directorios en LINUX

linux_dir(){

# Directorio de la instalacion
export D_LINUXCDGRAB="/usr/share/linux-cdgrab"
# Directorio para los parches
export D_PARCHES="/usr/share/linux-cdgrab/parches"
# Punto de montaje para Linux-cdgrab
export D_MNT="/mnt/lcdgrab"
# Punto de montaje del sistema operativo
export MNT="/mnt"
# Archivos temporales
export D_TMP="/tmp"
# Archivo de configuracion
export D_CFG="/etc"
# Ejecutables
export D_BIN="/usr/bin"

}

# gobolinux_dir
# directorios en GoboLINUX

gobolinux_dir(){

# Directorio de la instalacion
export D_LINUXCDGRAB="/Programs/linux-cdgrab-0.5"
# Directorio para los parches
export D_PARCHES="/Programs/linux-cdgrab-0.5/parches"
# Punto de montaje para Linux-cdgrab
export D_MNT="/Mount/lcdgrab"
# Punto de montaje del sistema operativo
export MNT="/Mount"
# Archivos temporales
export D_TMP="/Depot"
# Archivo de configuracion
export D_CFG="$D_LINUXCDGRAB"
# Ejecutables
export D_BIN="/System/Link/Executables"

}

# creditos
# Imprime los creditos

creditos(){
	
cat << ACERCA
$creditos_MSG1
$creditos_MSG2
		
$creditos_MSG3
		
$creditos_MSG4
		
ACERCA

}

# creacion_de_mnt
# Crea el directorio /mnt/cdrom en caso de que no exista
# en la distribucion de Linux.

creacion_de_mnt(){	
	
cat << EOF >$MNT/AVISO_PUNTO_DE_MONTAJE_CDROM.txt

$creacion_de_mnt_MSG1

$creacion_de_mnt_MSG2 $MNT/cdrom $creacion_de_mnt_MSG3
$creacion_de_mnt_MSG4
$creacion_de_mnt_MSG5 $MNT/cdrom.

$creacion_de_mnt_MSG6
$creacion_de_mnt_MSG7 $MNT/cdrom $creacion_de_mnt_MSG8
$creacion_de_mnt_MSG9

$creacion_de_mnt_MSG10 $MNT/cdrom
$creacion_de_mnt_MSG11
$creacion_de_mnt_MSG12 $MNT/cdrom

$creacion_de_mnt_MSG13

EOF

}

# ayuda
# Muestra la Ayuda de LINUX-CDGRAB.

# modificada 13-10-2014, añadida la comprobacion de vi en los directorios /bin y /usr/bin

ayuda(){

	editor_vi=""

# chequea /bin/vi y /usr/bin/vi

	if test -x /bin/vi;then
		editor_vi=/bin/vi
	fi

	if test -x /usr/bin/vi;then
		editor_vi=/usr/bin/vi
	fi

# los editores por defecto no estan instalados en el sistema.
# se da la posibilidad de abrir la ayuda con cualquiera existente.

	if test -z $editor_vi;then

		echo $ayuda_MSG1
		echo $ayuda_MSG2
		read editor

		if ($editor $D_LINUXCDGRAB/ayuda.txt);then
		echo ""
		else
			if test $UD -eq 0;then 
				dialog --backtitle "LINUX-CDGRAB 0.5" --msgbox $ayuda_MSG3 9 50
			else
				echo -e "${C_FA} $ayuda_MSG3 ${COLOR_DEL_INTERFAZ} ${FONDO_INTERFAZ}"
				teclash
			fi

		fi
	else
		$editor_vi $D_LINUXCDGRAB/ayuda.txt
	fi

	colores_interfaz

}

# exportar_variables
# Exporta variables al entorno

# exporta los diferentes parámetros de configuración.

exportar_variables(){

# exporta la forma de notificar mensajes

export UD

# exporta la velocidad de grabacion

export Velocidad="$( cat $D_CFG/lcdgrab.cfg | grep -e 'VELOCIDAD.' | sed -e 's/VELOCIDAD//g' -e 's/ //g' -e 's/[=]//g')"

# exporta el dispositivo de grabacion (tenga el valor que tenga,dispositivo de bloque o asignacion numerica de tipo X.Y.Z)

export IDE="$( cat $D_CFG/lcdgrab.cfg | grep -e 'IDE.' | sed -e 's/IDE//g' -e 's/ //g' -e 's/[=]//g')"

# exporta el lector de CD-ROM o DVD-ROM

export LECTOR_CDROM="$( cat $D_CFG/lcdgrab.cfg | grep -e 'LECTOR_CDROM.' | sed -e 's/LECTOR_CDROM//g' -e 's/ //g' -e 's/[=]//g')"

# exporta el dispositivo asignado a dev=ATAPI, variable CANALATAPI

export CANALATAPI="$( cat $D_CFG/lcdgrab.cfg | grep -e '.,.,.' | sed -e 's/CANALATAPI//g' -e 's/ //g' -e 's/[=]//g')"
# exporta el nivel ISO (por defecto vale 3)

export NIVEL_ISO

# exporta la grabadora de DVD usada para las dvd+-rw-tools
# si existe.En este caso IDE tiene un valor del tipo X.Y.Z

if ! test -z $grabadora_dvd;then
	export grabadora_dvd
fi

# exporta los colores.

export NEGRO
export ROJO
export VERDE
export AMARILLO
export AZUL
export MAGENTA
export CIAN
export GRIS
export DEFECTO
export STANDAR
export B_NEGRO
export B_ROJO
export B_VERDE
export B_AMARILLO
export B_AZUL
export B_MAGENTA
export B_CIAN
export B_BLANCO
export FONDO_NEGRO
export FONDO_ROJO
export FONDO_VERDE
export FONDO_NARANJA
export FONDO_AZUL
export FONDO_MAGENTA
export FONDO_CIAN
export FONDO_GRIS
export FONDO_DEFECTO
export C_OK
export C_FA
export C_AV
export C_ET

}

# cargar_parche
# Carga parches para linux - cdgrab

# Especificarle el nombre del parche

cargar_parche(){

echo "$cargar_parche_MSG1 $parche"
sleep 1

exportar_variables

$D_PARCHES/$parche


}

# lcdgrab_sintaxis
# Imprime la sintaxis de lcdgrab

lcdgrab_sintaxis(){

cat << EOF
$lcdgrab_sintaxis_MSG1 :
lcdgrab [-v]|[-h]|[-G=$lcdgrab_sintaxis_MSG12][-V=$lcdgrab_sintaxis_MSG13][-L=$lcdgrab_sintaxis_MSG12][-CA=$lcdgrab_sintaxis_MSG12]

-h  --help , $lcdgrab_sintaxis_MSG2
-v  --version , $lcdgrab_sintaxis_MSG3
-G  --grabadora , $lcdgrab_sintaxis_MSG4 -G=0,1,0 $lcdgrab_sintaxis_MSG5 -G=/dev/hdd
-V  --velocidad , $lcdgrab_sintaxis_MSG6 -V=32
-L  --lector , $lcdgrab_sintaxis_MSG7 -L=/dev/cdrom
-CA --canal-atapi , $lcdgrab_sintaxis_MSG8 -CA=0,0,0 o -CA=1,0,0

$lcdgrab_sintaxis_MSG9
$lcdgrab_sintaxis_MSG10

$lcdgrab_sintaxis_MSG11
lcdgrab -G=0,1,0 -L=/dev/hdc -V=16 -CA=0,1,0
lcdgrab --grabadora=/dev/hdd --lector=/dev/cdrom --velocidad=32 --canal-atapi=1,0,0
lcdgrab --help
lcdgrab --version
EOF

}

# idiom_cfg_def
# Carga el idioma que sera usado por defecto
# en la aplicacion

idiom_cfg_def(){

# Usa Idioma Español por defecto.

if test -d ${D_LINUXCDGRAB}/lcdgrabAPI_idiom/Español;then

	export IDIOM="Español"
	echo $IDIOM > $D_LINUXCDGRAB/UIIdiom.idiom
else
# Usa Idioma contenido en el directorio ./defectidiom
# Usa idioma por defecto que pueda residir en el directorio
# ${D_LINUXCDGRAB}/lcdgrabAPI_idiom/.defectidiom
# Corrige el caso donde el nombre de directorio del idioma
# Español se encuentre corrupto.
	export IDIOM=".defecidiom"
	echo $IDIOM > $D_LINUXCDGRAB/UIIdiom.idiom
fi

}


####################################################
############## PROGRAMA PRINCIPAL ##################
####################################################

## VARIABLES

# El modo iso en el que se deben crear las imagenes ISO-9660,consultar man mkisofs

NIVEL_ISO="3"

# Herramientas usadas por LINUX-CDGRAB

APLICACIONES="cdrecord cdda2wav mkisofs readcd cdrdao growisofs dvd+rw-format mke2fs bzip2 gzip xz bunzip2 gunzip unzip vi lame oggenc oggdec sox"

# Versión del programa

VERSION="LINUX-CDGRAB 0.5-r2 <Pascual Martinez Cruz, pascual89@hotmail.com>"

# Opcion de eleccion sobre el comando generador de iso para CD/DVD
# utiliso=1 --> opera con dd utiliso=2 --> opera con readcd

utiliso=1

# Opcion de chequeo para cdrkit.

notestcdrkit=0

## FIN VARIABLES

# exporta los directorios necesarios segun la distribucion.
# linux_dir para linux en general.
# gobolinux_dir exclusivo para la distribucion gobolinux.

if test -d /Programs;then
	#estamos bajo GOBOLINUX
	gobolinux_dir

	if test -d /System/Index/bin && test -x /System/Index/bin/lcdgrab;then
		export D_BIN="/System/Index/bin"
	elif test -d /Programs ;then
		export D_BIN="/Programs/linux-cdgrab-0.5"
    	else
        	echo $pgm_principal_MSG1
        	uname -a
	fi
else
	#estamos bajo Linux.
	linux_dir
fi

# establece el idioma usado por el interfaz de la aplicacion

if test -f ${D_LINUXCDGRAB}/UIIdiom.idiom;then
#	Carga idioma del fichero

	idiomatest=0
	IDIOMAARCHIVO="$(more ${D_LINUXCDGRAB}/UIIdiom.idiom)"

	for IDIOMA in `ls ${D_LINUXCDGRAB}/lcdgrabAPI_idiom`;do
		
		if  echo $IDIOMAARCHIVO | grep -e $IDIOMA &> /dev/null;then
			idiomatest=1
		fi

	done

	if test $idiomatest -eq 1 && test -d ${D_LINUXCDGRAB}/lcdgrabAPI_idiom/$IDIOMAARCHIVO;then
			export IDIOM="$(more ${D_LINUXCDGRAB}/UIIdiom.idiom)"
	else
# 		Utiliza Español por defecto cuando el fichero
# 		UIIdiom.idiom contenga una definicion corrupta de idioma.
		idiom_cfg_def
	fi
else
# 		Utiliza Español por defecto cuando el fichero
# 		UIIdiom.idiom no existe.
		idiom_cfg_def
fi

# carga el idioma usado en la aplicacion

source ${D_LINUXCDGRAB}/lcdgrabAPI_idiom/${IDIOM}/lcdgrab.idiom

# carga las APIs usadas por el programa

# API --> lcdgrabAPP_API; Procedimientos de soporte para la aplicacion.

source ${D_LINUXCDGRAB}/lcdgrabAPP_API/colores.dat
source ${D_LINUXCDGRAB}/lcdgrabAPP_API/lcdgrabAPP-SYS.sh

# API --> lcdgrabCMD_API; Funcionalidades de la aplicacion

source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabExpulsaCDDVD-API.sh
source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabCD-API.sh
source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabDVD-API.sh
source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabUNIDADES-API.sh
source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabCompresion-API.sh
source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabIMAGENESCDDVD-API.sh
source ${D_LINUXCDGRAB}/lcdgrabCMD_API/lcdgrabAUDIO-API.sh

# API --> lcdgrabMenu_API; Interfaces de Menu

source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUIMontajeUnidades.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUIGestorArchivos.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUITMPDIR.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUICentroControl.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUICD.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUIDVD.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUIUnidadesDisco.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUIIMAGENESCDDVD.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUIAUDIO.sh
source ${D_LINUXCDGRAB}/lcdgrabMenu_API/lcdgrabUICargaParches.sh

# Comprueba el Sistema operativo.

case $(uname -s) in

	"Linux")
		IDSISTEMA="LINUX"
	;;
	
	*)
		echo $main_IDSISTEMA_MSG1
		echo "------"
		echo $main_IDSISTEMA_MSG2
		echo $main_IDSISTEMA_MSG3
		echo ""
		
		IDSISTEMA=$pgm_principal_MSG2
		read XXXX-XXXX
	;;

esac

# trata los argumentos pasados a lcdgrab

if test $# -eq 4 || test $# -eq 1
then

	cont=4
	while test $cont -ne 0;do

	case $1 in

		'-v' | '--version')

			echo "$VERSION"
			echo ""
			exit 0
		;;
			
		'-h' | '--help')
			
			echo "$VERSION"
			echo ""
			lcdgrab_sintaxis
			exit 0 
		;;
			
		-G* | --grabadora*)
				
			IDE=$(echo $1 | sed -e 's/-G//g' -e 's/--grabadora//g' -e 's/[=]//g')
		;;

		-L* | --lector*)

			LECTOR_CDROM=$(echo $1 | sed -e 's/-L//g' -e 's/--lector//g' -e 's/[=]//g')
		;;

		-V* | --velocidad*)

			Velocidad=$(echo $1 | sed -e 's/-V//g' -e 's/--velocidad//g' -e 's/[=]//g')

		;;

		-CA* | --canal-atapi*)

			CANALATAPI=$(echo $1 | sed -e 's/-CA//g' -e 's/--canal-atapi//g' -e 's/[=]//g')

		;;
		
		*)
			
			echo -e "${ROJO}ERROR! lcdgrab $1 ${STANDAR}"
			echo -e "${ROJO}$1 $main_arg_MSG1 ${STANDAR}"
			echo ""
			lcdgrab_sintaxis
			exit 0
		;;


	esac

	shift
	let cont--
	done
	
	# genera el fichero de configuracion /etc/lcdgrab.cfg
	# con los argumentos pasados.

	nuevo_lcdgrabcfg $Velocidad $IDE $LECTOR_CDROM $CANALATAPI

elif test $# -ge 5;then

	echo -e "${ROJO}ERROR! lcdgrab $* ${STANDAR}"
	echo -e "${ROJO}$* $main_arg_MSG1 ${STANDAR}"
	echo ""
	lcdgrab_sintaxis
	exit 0
fi

# exporta los colores de la aplicacion al entorno
# para despues pintar el interfaz

colores_por_defecto

echo -e "$FONDO_INTERFAZ"
echo -e "$COLOR_DEL_INTERFAZ"

# Elige el interfaz para mostrar
# notificaciones al usuario.
# Si dialog esta instalado usara este sistema
# en caso contrario se usaran cadenas de texto.

selecciona_interfaz_de_notificacion			

# verifica si /mnt/cdrom existe

if ! test -d $MNT/cdrom;then

	mkdir $MNT &> /dev/null	
	mkdir $MNT/cdrom

	creacion_de_mnt
fi

# añade el directorio /opt/schily/bin al PATH en
# caso de no existir cdrecord,wodim, o cdda2wav o mkisofs.
# instalados por defecto en el sistema.
# Se necesita una compilacion de cdrtools
# instaladas en el sistema.

if ! test -x $D_BIN/cdrecord && ! test -x $D_BIN/wodim || ! test -x $D_BIN/cdda2wav || ! test -x $D_BIN/mkisofs;then
	# en el sistema no esta instalado ni cdrecord ni wodim 
	# o cdda2wav,o bien, mkisofs pueden ser faltantes
	# se chequea /opt/schily/bin por si existen las
	# cdrtools instaladas desde los propios fuentes.

	if test -d /opt/schily/bin;then
	
	# Se exporta el directorio al PATH

		export PATH=$PATH:/opt/schily/bin
		notestcdrkit=1
	fi
fi

# compatibilidad con cdrkit

if test $notestcdrkit -eq 0;then

	if ! test -x $D_BIN/cdrecord;then
		if test -x $D_BIN/wodim;then
			ln $D_BIN/wodim $D_BIN/cdrecord
			echo "$D_BIN/wodim $main_cdkit_test_MSG1"
			echo $main_cdkit_test_MSG2
			sleep 1
		 
		fi
	fi
	
	if ! test -x $D_BIN/mkisofs;then
		if test -x $D_BIN/genisoimage;then
			ln $D_BIN/genisoimage $D_BIN/mkisofs
			echo "$D_BIN/genisoimage $main_cdkit_test_MSG1"
			echo $main_cdkit_test_MSG3
			sleep 1
		fi
	fi

	if ! test -x $D_BIN/cdda2wav;then
		if test -x $D_BIN/icedax;then
			ln $D_BIN/icedax $D_BIN/cdda2wav
			echo "$D_BIN/icedax $main_cdkit_test_MSG1"
			echo $main_cdkit_test_MSG4
			sleep 1
		fi
	fi

fi

# exporta al entorno la opcion sobre generacion de imagenes
# iso desde CD.

export utiliso
		
# verifica si el fichero de configuracion existe
# si no existe se crea uno nuevo

clear

if test -f $D_CFG/lcdgrab.cfg;then
	leer_lcdgrabcfg
else
	nuevo_lcdgrabcfg
fi

### Menu principal de la aplicacion.
# Imprime el menu principal en pantalla.
# Pide seleccion de opciones al usuario.

while $verdadero;do

# Mensaje para el gestor de archivos

MSG=$MSG1_MAIN

clear

printf "=================================================\n"
printf "=\t\tLINUX-CDGRAB 0.5\t\t=\n"
printf "=\t\t----------------\t\t=\n"
printf "=================================================\n"
printf "=  1.- $main_lcdgrabop1\t\t\t\t=\n"
printf "=  2.- $main_lcdgrabop2\t\t\t\t=\n"
printf "=  3.- $main_lcdgrabop3\t\t=\n"
printf "=  4.- $main_lcdgrabop4\t\t\t=\n"
printf "=  5.- $main_lcdgrabop5\t\t\t=\n"
printf "=  6.- $main_lcdgrabop6\t\t=\n"
printf "=  7.- $main_lcdgrabop7\t\t=\n"
printf "=  8.- $main_lcdgrabop8\n"
printf "=  9.- $main_lcdgrabop9\t\t\t=\n"
printf "=  0.- $main_lcdgrabop0\t\t\t\t\t=\n"
printf "=================================================\n"
printf "=\t\t## $main_lcdgrabet1 ##\t\t=\n"
printf "=  -->> E o e: $main_lcdgrabopEe\t=\n"
printf "=  -->> TD: $main_lcdgrabopTD $D_TMP\t\t=\n"
printf "=  -->> G: $main_lcdgrabopG\t\t\t=\n"
printf "=  -->> H: $main_lcdgrabopH\t\t\t\t=\n"
printf "=  -->> A: $main_lcdgrabopA\t\t\t\t=\n"
printf "=================================================\n"

echo -n "		$main_lcdgrabopPRINCIPAL  "
read mainopcion

case $mainopcion in

	1)

		# llama al menu de grabacion de CD
		clear
		menugrabar_cd

	;;

	2)
		# llama al menu de grabacion de DVD

		clear
		SeleccionaIUDVD
	;;

	3)
		# llama al menu de operaciones sobre
		# dispositivos de bloque.

		clear
		MenuDispositivosBloque
	;;

	4)
		# llama al menu de creacion de imagenes

		clear
		MenuImagen
	;;

	5)	
		# llama al menu de conversion de audio

		clear
		menu_conversion_audio
	;;

	6)
		# Monta o desmonta dispositivos de bloque
		
		montar_dispositivos $LECTOR_CDROM

	;;

	7)
		# Monta o desmonta imagenes .iso o .ext2

		Montar_Imagenes

		;;

	8)
	
		# Gestiona la carga de parches

		cargar_parche

	;;

	9)
		# muestra el centro de control

		clear
		centro_de_control

	;;

	"E" | "e")
		# Expulsa un disco optico de las unidades fisicas

		expulsar_medio $IDE

	;;

	"TD")
		# muestra interfaz para el directorio de archivos temporales

		dir_tmp

	;;

	"dep")
		# ejecuta linux-cdgrab en modo de depuracion 

		if test -x $D_BIN/lcdgrab;then

			bash -x $D_BIN/lcdgrab
		else
			echo ""
			echo $main_lcdgrabopdep_MSG1
			read r_script

			if ! [ -z $r_script ];then
				bash -x $r_script
			else
				echo $main_lcdgrabopdep_MSG2
				sleep 0.5
			fi
		
		fi

	;;

	"deppatch")
		
		# ejecuta un parche para linux-cdgrab en modo de depuracion

		clear
		cabecera
		echo $main_lcdgrabopdeppatch_MSG1
		echo "###################"
		echo ""
		ls $D_PARCHES/*.sh
	
		echo $main_lcdgrabopdeppatch_MSG2
		read r_parche

		if test -x $r_parche;then

			bash -x $r_parche && exportar_variables
		
		else
			echo "$main_lcdgrabopdeppatch_MSG3 $r_parche"
			teclash
		fi
	;;

	"logo")
		# Imprime el logo

		logo
	;;

	"G")
		# lanza el gestor de archivos

		gestor_de_archivos $MSG
	;;

	"H")
		# muestra la ayuda

		clear
		ayuda
	;;

	"A")
		# Muestra los creditos

		clear
		cabecera
		echo "${VERSION}"
		creditos
		echo $main_lcdgrabopA_MSG1
		echo " $(uname -a)"
		read creditos

	;; 
		
	0)
		# sale del programa
		rm -rf $D_LINUXCDGRAB/lcdgrabnombreruta.*
		rm -rf $D_LINUXCDGRAB/*comprimir*
		export COLOR_DEL_INTERFAZ=$STANDAR
		echo -e "${COLOR_DEL_INTERFAZ}"
		clear
	
		break
	;;

	*)	# opciones incorrectas

		clear
		if test $UD -eq 0;then
			Opcion_invalida
			colores_interfaz
		else
			text_Opcion_invalida
			sleep 1
		fi
		continue
	;;

esac

done
